openapi: 3.0.1
info:
  title: BudgetTracker - Subset
  version: '1.0'
servers:
- url: https://localhost:7196
paths:
  /budgets:
    get:
      tags:
      - BudgetsEndpoint
      summary: Get budgets based on budget name
      description: 'Returns details including name and available funds of budgets, optionally filtered by budget name'
      operationId: GetBudgets
      parameters:
      - name: budgetName
        in: query
        description: The name of the budget to retrieve
        style: form
        explode: false
        schema:
          type: string
      responses:
        2XX:
          description: OK
          content:
            text/plain:
              schema:
                type: string
    post:
      tags:
      - BudgetsEndpoint
      summary: Create a new budget
      description: Create a new budget with a specified name and available funds
      operationId: CreateBudget
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Budget'
        required: true
      responses:
        2XX:
          description: Created
          content:
            text/plain:
              schema:
                type: string
  /budgets/charge:
    post:
      tags:
      - BudgetsEndpoint
      summary: Charge an amount to a budget
      description: Charge an amount to a budget with a specified name. This removes the specified amount from the budget's available funds
      operationId: ChargeBudget
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
        required: true
      responses:
        2XX:
          description: Accepted
          content:
            text/plain:
              schema:
                type: string
  /budgets/extend:
    post:
      tags:
      - BudgetsEndpoint
      summary: Add an amount to a budget
      description: Add an amount to a budget with a specified name. This adds the specified amount to the budget's available funds
      operationId: ExtendBudget
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
        required: true
      responses:
        2XX:
          description: Accepted
          content:
            text/plain:
              schema:
                type: string
  /transactions:
    get:
      tags:
      - TransactionsEndpoint
      summary: Get transactions based on budget name or category
      description: Returns details of transactions identified from filters like budget name or category. Multiple filters can be used in combination to refine the list of transactions returned
      operationId: GetTransactions
      parameters:
      - name: budgetName
        in: query
        description: The name of the budget to filter results on
        style: form
        explode: false
        schema:
          type: string
      - name: category
        in: query
        description: The name of the category to filter results on
        style: form
        explode: false
        schema:
          type: string
      responses:
        2XX:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /transactions/send:
    post:
      tags:
      - TransactionsEndpoint
      summary: Send a transaction report to my email
      description: 'Sends a transaction report via email, optionally filtered by budget.'
      operationId: SendTransactionReport
      parameters:
      - name: budgetName
        in: query
        description: The name of the budget to filter report on
        style: form
        explode: false
        schema:
          type: string
      responses:
        2XX:
          description: Accepted
          content:
            text/plain:
              schema:
                type: string
      x-openai-isConsequential: false
components:
  schemas:
    Budget:
      required:
      - availableFunds
      - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
          description: Gets or sets the name of the budget.
          example: Contoso Copilot plugin project
        availableFunds:
          type: number
          description: Gets or sets the available funds in the budget.
          format: double
          example: 50000
      additionalProperties: false
      description: Represents a project budget.
    Transaction:
      required:
      - amount
      - budgetName
      - description
      type: object
      properties:
        budgetName:
          minLength: 1
          type: string
          description: Gets or sets the name of the budget to adjust.
          example: Contoso Copilot plugin project
        amount:
          type: number
          description: Gets or sets the amount of the adjustment.
          format: double
          example: -5000
        description:
          minLength: 1
          type: string
          description: Gets or sets a description for the change.
          example: Purchase new laptops for team
        expenseCategory:
          type: string
          description: Gets or sets the expense category for charges against the budget.
          nullable: true
          example: hardware
      additionalProperties: false
      description: Represents a change to a budget's available funds.
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/{tenant-id}/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/{tenant-id}/oauth2/v2.0/token
          scopes:
            api://{client-id}/.default: Access Budget Tracker as you
security:
- OAuth2:
  - api://{client-id}/.default
